import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="con">
            <h1>
              <Link href={"/"}>
                <img src="/logo_color.svg" />
              </Link>
            </h1>
            <nav id="gnb">
              <ul>
                <li>
                  <Link href={"/"}>Q&amp;A</Link>
                </li>
                <li>
                  <Link href={"/"}>지식</Link>
                </li>
                <li>
                  <Link href={"/community/1"}>커뮤니티</Link>
                </li>
              </ul>
            </nav>
            <Link href={"/account"}>
              <button className="login">
                <img src="/person.svg" alt="login" />
                <span>로그인</span>
              </button>
            </Link>
          </div>
        </header>
        {children}
        <footer>
          <div className="con">
            <h2>
              <Link href={"/"}>
                <img src="/footer_logo.svg" />
              </Link>
            </h2>
            <p>&copy; 2023 BitHarbor. all rights reserved.</p>
            <div className="sns-icons">
              <ul>
                <li>
                  <Link
                    href={
                      "https://www.notion.so/side-project-04b609ff07564e41a5cdbb3f54523c8f?pvs=4"
                    }
                  >
                    <img src="/notion_button.svg" alt="notion" />
                  </Link>
                </li>
                <li>
                  <Link href={""}>
                    <img src="/git_button.svg" alt="notion" />
                  </Link>
                </li>
                <li>
                  <Link
                    href={
                      "https://www.figma.com/file/lZTKPzCMlPT8kMHdwgs4B7/main_page?type=design&node-id=44%3A33733&mode=design&t=MvuVAV1e1zPyfoh5-1"
                    }
                  >
                    <img src="/figma_button.svg" alt="notion" />
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
